// Stamps a build identifier into the app so a build actually running on a
// device (webOS install, browser cache) can be told apart from an older one
// at a glance — otherwise "did the reinstall even take" is unanswerable from
// the UI alone. Runs automatically before `ng serve`/build via npm's pre-hook
// convention (see package.json's "prestart"/"prepackage:webos" scripts).
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

let commit = "nogit";
try {
  commit = execSync("git rev-parse --short HEAD", { cwd: path.join(__dirname, "..") }).toString().trim();
} catch {
  // Not in a git checkout (e.g. an extracted release) — timestamp alone still disambiguates builds.
}

// Local time, not UTC — this is read by a person checking "did my rebuild
// just now actually land," so it should match the clock they're looking at.
const now = new Date();
const pad = (n) => String(n).padStart(2, "0");
const builtAt = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}`;
const content = `// Auto-generated by scripts/generate-version.js on every build — do not edit.
export const APP_VERSION = "${commit} · ${builtAt}";
`;

fs.writeFileSync(path.join(__dirname, "..", "src", "app", "version.ts"), content);
console.log(`Generated version.ts: ${commit} · ${builtAt}`);
